
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class TicTacToe extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToe
     */
    public TicTacToe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PlayerX = new javax.swing.JCheckBox();
        PlayerO = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        B8 = new javax.swing.JButton();
        B9 = new javax.swing.JButton();
        CLEAR = new javax.swing.JButton();
        RESET = new javax.swing.JButton();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));
        setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 255, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");

        PlayerX.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(PlayerX);
        PlayerX.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PlayerX.setForeground(new java.awt.Color(153, 0, 204));
        PlayerX.setSelected(true);
        PlayerX.setText("Player X");

        PlayerO.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(PlayerO);
        PlayerO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PlayerO.setForeground(new java.awt.Color(153, 0, 204));
        PlayerO.setText("Player O");
        PlayerO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerOActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));
        jPanel2.setForeground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 3, 5, 5));

        B1.setBackground(new java.awt.Color(255, 255, 255));
        B1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B1.setText("?");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel2.add(B1);

        B2.setBackground(new java.awt.Color(255, 255, 255));
        B2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B2.setText("?");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel2.add(B2);

        B3.setBackground(new java.awt.Color(255, 255, 255));
        B3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B3.setText("?");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel2.add(B3);

        B4.setBackground(new java.awt.Color(255, 255, 255));
        B4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B4.setText("?");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        jPanel2.add(B4);

        B5.setBackground(new java.awt.Color(255, 255, 255));
        B5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B5.setText("?");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        jPanel2.add(B5);

        B6.setBackground(new java.awt.Color(255, 255, 255));
        B6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B6.setText("?");
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        jPanel2.add(B6);

        B7.setBackground(new java.awt.Color(255, 255, 255));
        B7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B7.setText("?");
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        jPanel2.add(B7);

        B8.setBackground(new java.awt.Color(255, 255, 255));
        B8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B8.setText("?");
        B8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B8ActionPerformed(evt);
            }
        });
        jPanel2.add(B8);

        B9.setBackground(new java.awt.Color(255, 255, 255));
        B9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        B9.setText("?");
        B9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B9ActionPerformed(evt);
            }
        });
        jPanel2.add(B9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PlayerX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PlayerO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerX)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
        );

        CLEAR.setBackground(new java.awt.Color(255, 255, 255));
        CLEAR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(255, 0, 0));
        CLEAR.setText("CLEAR");
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        RESET.setBackground(new java.awt.Color(255, 255, 255));
        RESET.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RESET.setForeground(new java.awt.Color(255, 0, 0));
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(391, Short.MAX_VALUE)
                .addComponent(CLEAR)
                .addGap(52, 52, 52)
                .addComponent(RESET)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLEAR)
                    .addComponent(RESET))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayerOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlayerOActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        // TODO add your handling code here:
        Buttons(B7);
        if(Winner(B7,B1,B4)){}
        else if(Winner(B7,B5,B3)){}
        else if(Winner(B7,B8,B9)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B7ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        Buttons(B1);
        if(Winner(B1,B2,B3)){}
        else if(Winner(B1,B5,B9)){}
        else if(Winner(B1,B4,B7)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
                    // TODO add your handling code here:
                    Buttons(B2);
                    if(Winner(B2,B5,B8)){}
                    else if(Winner(B2,B1,B3)){}
                    else{
            Draw();
        }
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        Buttons(B3);
        if(Winner(B3,B5,B7)){}
        else if(Winner(B3,B1,B2)){}
        else if(Winner(B3,B6,B9)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        // TODO add your handling code here:
        Buttons(B4);
        if(Winner(B4,B1,B7)){}
        else if(Winner(B4,B5,B6)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        // TODO add your handling code here:
        Buttons(B5);
        if(Winner(B5,B2,B8)){}
        else if(Winner(B5,B4,B6)){}
        else if(Winner(B5,B1,B9)){}
        else if(Winner(B5,B3,B7)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B5ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        // TODO add your handling code here:
        Buttons(B6);
        if(Winner(B6,B3,B9)){}
        else if(Winner(B6,B4,B5)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B6ActionPerformed

    private void B8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B8ActionPerformed
        // TODO add your handling code here:
        Buttons(B8);
        if(Winner(B8,B2,B5)){}
        else if(Winner(B8,B7,B9)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B8ActionPerformed

    private void B9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B9ActionPerformed
        // TODO add your handling code here:
        Buttons(B9);
        if(Winner(B9,B3,B6)){}
        else if(Winner(B9,B5,B1)){}
        else if(Winner(B9,B7,B8)){}
        else{
            Draw();
        }
    }//GEN-LAST:event_B9ActionPerformed

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
        B1.setText("?");
        B2.setText("?");
        B3.setText("?");
        B4.setText("?");
        B5.setText("?");
        B6.setText("?");
        B7.setText("?");
        B8.setText("?");
        B9.setText("?");
        B1.setBackground(Color.white);
        B2.setBackground(Color.white);
        B3.setBackground(Color.white);
        B4.setBackground(Color.white);
        B5.setBackground(Color.white);
        B6.setBackground(Color.white);
        B7.setBackground(Color.white);
        B8.setBackground(Color.white);
        B9.setBackground(Color.white);
        
        
        
    }//GEN-LAST:event_CLEARActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        // TODO add your handling code here:
        this.dispose();
        main(null);
    }//GEN-LAST:event_RESETActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton B8;
    private javax.swing.JButton B9;
    private javax.swing.JButton CLEAR;
    private javax.swing.JCheckBox PlayerO;
    private javax.swing.JCheckBox PlayerX;
    private javax.swing.JButton RESET;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
public void Buttons(JButton button){
    String a = button.getText();
    if(a.equals("?")){
        if(PlayerX.isSelected()){
            button.setText("X");
            PlayerO.setSelected(true);
        }else if(PlayerO.isSelected()){
            button.setText("O");
            PlayerX.setSelected(true);
        }
        }
    }
public boolean Winner(JButton b1,JButton b2,JButton b3){
    String a=b1.getText();
    String b=b2.getText();
    String c = b3.getText();
    if(a.equals(b) && a.equals(c)){
       b1.setBackground(Color.yellow);
       b2.setBackground(Color.yellow);
       b3.setBackground(Color.yellow);
       JOptionPane.showMessageDialog(this,"<html><h1> "+a+" WIN!</h1></html>");
       CLEARActionPerformed(null);
       return true;
    } else{
        return false;
    }
}
public void  Draw(){
    String a=B1.getText();
    String b=B2.getText();
    String c=B3.getText();
    String d=B4.getText();
    String e=B5.getText();
    String f=B6.getText();
    String g=B7.getText();
    String h=B8.getText();
    String i=B9.getText();
    if(!a.equals("?") && !b.equals("?") && !c.equals("?") && !d.equals("?") && !e.equals("?") && !f.equals("?") && !g.equals("?")&& !h.equals("?") && !i.equals("?")){
    JOptionPane.showMessageDialog(this,"<html><h1>DRAW!</h1></html>");
    CLEARActionPerformed(null);
}
    
}
}




